name = "fitday-ai"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"


[[d1_databases]]
binding = "FITNESS_DB"
database_name = "fitday-ai-db"
database_id = "42dfee08-f14f-4e08-938d-6fdebab4700e"